# Use an official Node.js runtime as a parent image
FROM node:14

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY . . 

# Install project dependencies
RUN npm install

# Expose the port for HMR
EXPOSE 5173

# Start the development server
CMD ["npm", "run", "dev"]
